version: '3.9'

services:
  selenium_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "5900:5900" # Example: forward port if needed
    environment:
      - DISPLAY=:99
    tty: true
    command: tail -f /dev/null
  